services:

  app:
    build:
      context: .
      target: app
    volumes:
      - .:/var/www/symfony
    environment:
      APP_ENV: ${APP_ENV}
      DATABASE_URL: ${DATABASE_URL}
      MAILER_DSN: ${MAILER_DSN}
    depends_on:
      database:
        condition: service_healthy
      mailer:
        condition: service_started

  mailer:
    image: axllent/mailpit:latest
    ports:
      - "8026:8025"  # Interface web

  nginx:
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/symfony/public:ro
    depends_on:
      - app


  database:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: app
      MARIADB_PASSWORD: app
      MARIADB_DATABASE: portfolio_db

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
