<?php

namespace ContainerEMsTwVD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sV5Hrrz.App\Controller\Admin\AdminProjectController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'project' => ['privates', '.errored..service_locator.sV5Hrrz.App\\Entity\\Projects', NULL, 'Cannot autowire service ".service_locator.sV5Hrrz": it needs an instance of "App\\Entity\\Projects" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'em' => '?',
            'project' => 'App\\Entity\\Projects',
        ]))->withContext('App\\Controller\\Admin\\AdminProjectController::edit()', $container);

        if (isset($container->privates['.service_locator.sV5Hrrz.App\\Controller\\Admin\\AdminProjectController::edit()'])) {
            return $container->privates['.service_locator.sV5Hrrz.App\\Controller\\Admin\\AdminProjectController::edit()'];
        }

        return $container->privates['.service_locator.sV5Hrrz.App\\Controller\\Admin\\AdminProjectController::edit()'] = $instance;
    }
}
