<?php

namespace Container6lFfWXQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oBR0Fri.App\Controller\Admin\AdminProjectController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'project' => ['privates', '.errored..service_locator.oBR0Fri.App\\Entity\\Projects', NULL, 'Cannot autowire service ".service_locator.oBR0Fri": it needs an instance of "App\\Entity\\Projects" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'project' => 'App\\Entity\\Projects',
            'em' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminProjectController::delete()', $container);

        if (isset($container->privates['.service_locator.oBR0Fri.App\\Controller\\Admin\\AdminProjectController::delete()'])) {
            return $container->privates['.service_locator.oBR0Fri.App\\Controller\\Admin\\AdminProjectController::delete()'];
        }

        return $container->privates['.service_locator.oBR0Fri.App\\Controller\\Admin\\AdminProjectController::delete()'] = $instance;
    }
}
