<?php

namespace ContainerUGMOEOa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VSHsG5bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VSHsG5b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminProjectController::projectIndex' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\Admin\\AdminProjectController::projectIndex()', 'getAdminProjectControllerprojectIndexService', true],
            'App\\Controller\\Admin\\AdminProjectController::show' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\Admin\\AdminProjectController::show()', 'getAdminProjectControllershowService', true],
            'App\\Controller\\Admin\\AdminProjectController::new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\AdminProjectController::new()', 'getAdminProjectControllernewService', true],
            'App\\Controller\\Admin\\AdminProjectController::edit' => ['privates', '.service_locator.sV5Hrrz.App\\Controller\\Admin\\AdminProjectController::edit()', 'getAdminProjectControllereditService', true],
            'App\\Controller\\Admin\\AdminProjectController::delete' => ['privates', '.service_locator.oBR0Fri.App\\Controller\\Admin\\AdminProjectController::delete()', 'getAdminProjectControllerdeleteService', true],
            'App\\Controller\\ContactController::index' => ['privates', '.service_locator.heJ666n.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\ProjectController::index' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\ProjectController::index()', 'getProjectControllerindexService', true],
            'App\\Controller\\ProjectController::show' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\ProjectController::show()', 'getProjectControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminProjectController:projectIndex' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\Admin\\AdminProjectController::projectIndex()', 'getAdminProjectControllerprojectIndexService', true],
            'App\\Controller\\Admin\\AdminProjectController:show' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\Admin\\AdminProjectController::show()', 'getAdminProjectControllershowService', true],
            'App\\Controller\\Admin\\AdminProjectController:new' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Admin\\AdminProjectController::new()', 'getAdminProjectControllernewService', true],
            'App\\Controller\\Admin\\AdminProjectController:edit' => ['privates', '.service_locator.sV5Hrrz.App\\Controller\\Admin\\AdminProjectController::edit()', 'getAdminProjectControllereditService', true],
            'App\\Controller\\Admin\\AdminProjectController:delete' => ['privates', '.service_locator.oBR0Fri.App\\Controller\\Admin\\AdminProjectController::delete()', 'getAdminProjectControllerdeleteService', true],
            'App\\Controller\\ContactController:index' => ['privates', '.service_locator.heJ666n.App\\Controller\\ContactController::index()', 'getContactControllerindexService', true],
            'App\\Controller\\ProjectController:index' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\ProjectController::index()', 'getProjectControllerindexService', true],
            'App\\Controller\\ProjectController:show' => ['privates', '.service_locator.F9uMLyC.App\\Controller\\ProjectController::show()', 'getProjectControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminProjectController::projectIndex' => '?',
            'App\\Controller\\Admin\\AdminProjectController::show' => '?',
            'App\\Controller\\Admin\\AdminProjectController::new' => '?',
            'App\\Controller\\Admin\\AdminProjectController::edit' => '?',
            'App\\Controller\\Admin\\AdminProjectController::delete' => '?',
            'App\\Controller\\ContactController::index' => '?',
            'App\\Controller\\ProjectController::index' => '?',
            'App\\Controller\\ProjectController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminProjectController:projectIndex' => '?',
            'App\\Controller\\Admin\\AdminProjectController:show' => '?',
            'App\\Controller\\Admin\\AdminProjectController:new' => '?',
            'App\\Controller\\Admin\\AdminProjectController:edit' => '?',
            'App\\Controller\\Admin\\AdminProjectController:delete' => '?',
            'App\\Controller\\ContactController:index' => '?',
            'App\\Controller\\ProjectController:index' => '?',
            'App\\Controller\\ProjectController:show' => '?',
        ]);

        if (isset($container->privates['.service_locator.VSHsG5b'])) {
            return $container->privates['.service_locator.VSHsG5b'];
        }

        return $container->privates['.service_locator.VSHsG5b'] = $instance;
    }
}
