<?php

namespace ContainerBa63Dgx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F9uMLyC.App\Controller\Admin\AdminProjectController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F9uMLyC.App\\Controller\\Admin\\AdminProjectController::show()'] = ($container->privates['.service_locator.F9uMLyC'] ?? $container->load('get_ServiceLocator_F9uMLyCService'))->withContext('App\\Controller\\Admin\\AdminProjectController::show()', $container);
    }
}
