<?php

namespace ContainerRxLlpZZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5x3l3QW.App\Controller\Admin\AdminProjectController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5x3l3QW.App\\Controller\\Admin\\AdminProjectController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projectsRepository' => ['privates', 'App\\Repository\\ProjectsRepository', 'getProjectsRepositoryService', true],
            'project' => ['privates', '.errored..service_locator.5x3l3QW.App\\Entity\\Projects', NULL, 'Cannot autowire service ".service_locator.5x3l3QW": it needs an instance of "App\\Entity\\Projects" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'projectsRepository' => 'App\\Repository\\ProjectsRepository',
            'project' => 'App\\Entity\\Projects',
        ]))->withContext('App\\Controller\\Admin\\AdminProjectController::delete()', $container);
    }
}
