<?php

namespace ContainerRxLlpZZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.heJ666n.App\Controller\ContactController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'mailer' => '?',
        ]))->withContext('App\\Controller\\ContactController::index()', $container);

        if (isset($container->privates['.service_locator.heJ666n.App\\Controller\\ContactController::index()'])) {
            return $container->privates['.service_locator.heJ666n.App\\Controller\\ContactController::index()'];
        }

        return $container->privates['.service_locator.heJ666n.App\\Controller\\ContactController::index()'] = $instance;
    }
}
