<?php

namespace ContainerRxLlpZZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjectsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5x3l3QW.App\Entity\Projects' shared service.
     *
     * @return \App\Entity\Projects
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5x3l3QW": it needs an instance of "App\\Entity\\Projects" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
