<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyj2ZuH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyj2ZuH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyj2ZuH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyj2ZuH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyj2ZuH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xyj2ZuH',
    'container.build_id' => '193f67c7',
    'container.build_time' => 1777737655,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyj2ZuH');
